# Generated by Django 5.0 on 2023-12-16 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_meds_medid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meds',
            old_name='medType',
            new_name='dosageForm',
        ),
        migrations.RemoveField(
            model_name='meds',
            name='dosage',
        ),
    ]
